version: '2'
services:
    pedido-app:
        image: pedido
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://pedido-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=pedido
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    pedido-mongodb:
        extends:
            file: mongodb.yml
            service: pedido-mongodb
