version: '2'
services:
    produto-app:
        image: produto
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://produto-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=produto
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    produto-mongodb:
        extends:
            file: mongodb.yml
            service: produto-mongodb
